### ISSUE TITLE
Ability to update OSM configurations outside of configmap

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#2085]
**Please describe the Improvement and/or Feature Request**
Day 2 operations and beyond, the ability to make inline changes to OSM configurations without the need to manipulate the initial configmap

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Changing the mode of the running service mesh permissive mode value

**Comment by draychev** [comment]
The goal of this issue is to provide a CLI command/option for every parameter available in the OSM ConfigMap. Context: patching the config map from command line is difficult and error prone; providing a CLI command would improve the user experience.

Related issues:
  - [ ] https://github.com/openservicemesh/osm/issues/1855 [OSM CLI: provide a way to toggle ConfigMap permissive_traffic_policy_mode true/false #1855](https://github.com/openservicemesh/osm/issues/1855) 
  - [ ] https://github.com/openservicemesh/osm/issues/1139 [update osm-controller/control plane configuration via the osm cli #1139](https://github.com/openservicemesh/osm/issues/1139)
  - [ ] https://github.com/openservicemesh/osm/issues/1501 [Make pkg/catalog Ticker announcement channel configurable #1501 ](https://github.com/openservicemesh/osm/issues/1501)
  - [ ] https://github.com/openservicemesh/osm/issues/2290 [osm-controller's debug-server does not toggle off -> on as expected #2290 ](https://github.com/openservicemesh/osm/issues/2290)

**Comment by shashankram** [comment]
As a part of the upgrade effort, we have decided to use a custom resource called `MeshConfig` for users to tweak control plane configurations. This is the recommended workflow and there is no plan to support tweaking the same parameters through a CLI command. In fact, a decision was made to remove code from CLI that pertains to updating control plane configuration as a part of https://github.com/openservicemesh/osm/issues/3212.
