### ISSUE TITLE
Envoy must expose health probes of underlying service 

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2207]
When an Envoy sidecar is injected, the Envoy must preserve the existing health probes configured on the Pod.

Currently - when a Pod w/ health probes is injected w/ OSM Envoy, health probes fail.

Related:
  - [ ] https://github.com/openservicemesh/osm/issues/2097  **Program ip:port combinations as possible host headers in virtual_host.domains for HTTP routes**
  - [x] https://github.com/openservicemesh/osm/issues/1420  **Not working with dapr**
  - [x] https://github.com/openservicemesh/osm/issues/1975  **Failing local service cluster with target port of service**
  - [x] Support for TCP and gRPC readiness, liveness and startup probes #2543
  - [x] Bug in Liveness/Readiness rewriting for HTTPS probes #2515

**Comment by draychev** [comment]
Status Update:  The health probes are merged and will be released with v0.7
There needs to be an extensive test written for this functionality. This will come with: https://github.com/openservicemesh/osm/pull/2269

**Comment by shashankram** [comment]
@draychev we should also note that this only support HTTP/HTTPS probes, and not TCP probes.

**Comment by draychev** [comment]
New (similar) issue: **Support for TCP and gRPC readiness, liveness and startup probes** #2543

**Comment by draychev** [comment]
With  #3122  done - we can close this.
