### ISSUE TITLE
Milestone v0.9.0 planning 

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2611]
Please refer to issues you'd like to see resolved in comments on this thread.

**Comment by michelleN** [comment]
#2369

**Comment by SanyaKochhar** [comment]
https://github.com/openservicemesh/osm/issues/2585

**Comment by shashankram** [comment]
https://github.com/openservicemesh/osm/issues/2356
https://github.com/openservicemesh/osm/issues/2508
https://github.com/openservicemesh/osm/issues/2365
https://github.com/openservicemesh/osm/issues/2263
https://github.com/openservicemesh/osm/issues/2218
https://github.com/openservicemesh/osm/issues/2472
https://github.com/openservicemesh/osm/issues/2453
https://github.com/openservicemesh/osm/issues/2172

**Comment by snehachhabria** [comment]
https://github.com/openservicemesh/osm/issues/2369
https://github.com/openservicemesh/osm/issues/2368
https://github.com/openservicemesh/osm/issues/2654

**Comment by shashankram** [comment]
Upgrade related:
https://github.com/openservicemesh/osm/issues/2737
https://github.com/openservicemesh/osm/issues/2738

**Comment by draychev** [comment]
My proposal:

### Continuing work from v0.8
  - [ ] v0.8 documentation #2854

### Integrations
  - [ ] Integrate w/ Dapr #2875

### Upgrade Story
  - [ ] Proposal: Use a CRD instead of ConfigMap for OSM configuration #2738 
    - [ ] config: Design a new OSM Config CRD (YAML only) #3033
    - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
    - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
    - [ ] config: Generate Go Client code for new OSM Config CRD #3037
    - [ ] config: Create new Configuration CRD informers #3038
    - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
    - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040

**Comment by bridgetkromhout** [comment]
As discussed in the planning meeting, let's also add [Implement SMI Metrics #379](https://github.com/openservicemesh/osm/issues/379).
