### ISSUE TITLE
(root) Use a CRD instead of ConfigMap for OSM configuration

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2738]
This is the root issue for an accepted proposal to convert the `osm-config` ConfigMap to a [CustomResourceDefinition](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/).

The work to complete this root issue is comprised of the following (ordered) tasks:
  - [x] config: Design a new OSM Config CRD (YAML only) #3033
  - [x] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [x] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [x] config: Generate Go Client code for new OSM Config CRD #3037
  - [x] config: Create new Configuration CRD informers #3038
  - [x] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [x] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [x] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041
  - [x] deprecate the use of `osm mesh upgrade` for configmap changes #3212 
  - [x] Delete this issue:  https://github.com/openservicemesh/osm/issues/2932

---

Currently OSM relies on the `osm-config` ConfigMap to store control plane configurations. This has served us well so far and has been easy to maintain. However, complications arise when we want to version the configurations and provide a migration strategy since the ConfigMap is simply a collection of key value pairs.

This is a proposal to implement a CRD for OSM control plane configurations so that the configuration options can be versioned, migrated, deprecated etc. to provide a seamless upgrade path to users.
In addition, to keep OSM backward compatible, the proposal does not aim to deprecate the `osm-config` ConfigMap immediately, but rather over a period of time when existing users have been migrated to use the custom OSM config resource based on the CRD.

Versioning migration can be handled using a conversion webhook: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
To support versioning, migration, and deprecation of OSM control plane configurations.

**Comment by draychev** [comment]
Some past context:  https://github.com/openservicemesh/osm/issues/465

**Comment by draychev** [comment]
Overall I am in support of working towards switching from ConfigMap to CRD.

---

To add to @shashankram's excellent description of the issue
> This has served us well so far and has been easy to maintain.

Current state of the `osm-system/osm-config` ConfigMap:

```bash
$ kubectl get ConfigMap -n osm-system osm-config -o json | jq '.data'
```
```json
{
  "egress": "false",
  "enable_debug_server": "true",
  "enable_privileged_init_container": "false",
  "envoy_log_level": "trace",
  "permissive_traffic_policy_mode": "false",
  "prometheus_scraping": "true",
  "service_cert_validity_duration": "24h",
  "tracing_enable": "false",
  "use_https_ingress": "false"
}
```

Current ConfigMap relies on JSON encoded in the `data` field. As @shashankram already pointed out - this is not versioned. At some point we will need to make changes to the map:
 1. rename a field (example: `enable_debug_server` -> `enable_debugger`)
 2. delete a field (`use_https_ingress`)
 3. add a new field (recent example: `enable_privileged_init_container`)
 4. change the possible values / enums for a field (`"envoy_log_level": "warning"` -> `"envoy_log_level": "warn"`)

If we decided to continue with a ConfigMap and JSON, we would most likely need to:
 - somehow add version for the JSON in the `data` field - we could use annotations, add version in the JSON itself etc.
 - we'll need to establish rules like: 
     - delete a field should be deprecate (annotate), not actually delete
     - rename should be addition of a new field and deprecation (keeping but annotating) of an old field, not add/delete

Coexistence of 2 ConfigMaps (old version and new version) would be hacky at best. (Imagine having to rollback to a previous version of a ConfigMap due to a failed upgrade. How do we restore a previous version? We can copy old ConfigMap to a new one w/ different name and version; we can stuff old version of ConfigMap in a field of the new one etc. - all hacks)

---

Having a versioned CRD, as @shashankram pointed out:
 - solves the versioning issue
 - has an established migration path via conversion webhook
 - we can have more than one version of the ConfigMap (now CRD) in the same Namespace - makes it easier to rollback
 - we will add validation to the CRD so wrong keys and values are instantly reported to the user (at `kubectl apply` time)

cons:
 - adding/removing fields becomes much more time-consuming
 - we'll need to rewrite areas of the codebase that currently rely on the properties of the ConfigMap (will take some non-zero time)

**Comment by draychev** [comment]
Follow up issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040

**Comment by snehachhabria** [comment]
Remaining work items : 

- [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040 - only item pending here is to generate the api doc ( I will handle this early next week) 
- [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041
- [ ] Remove intermediate data structure osm-config #3268
- [ ]

**Comment by snehachhabria** [comment]
closing this issue as all the work done to switch over from configmap to a CRD is done, there is a follow upon upgrades of CRD's which will be tracked with issue #3396
