### ISSUE TITLE
CI intermitent failures 

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#2749]
We are chasing some bugs on CI (different from https://github.com/openservicemesh/osm/issues/2661) that occur intermittently on (allegedly, to be confirmed) TCP route e2e tests.

It seems the client envoy receives a `Unknown error code 104 details Connection reset by peer`, we don't see any relevant logs on the server side that points why is this happening though.

Last failure observed: https://github.com/openservicemesh/osm/runs/2041825948?check_suite_focus=true

Timestamp correlated logs for a given connection attempt:

Client side:
```
2021-03-05T18:00:21.062047371Z stderr F [2021-03-05 18:00:21.061][14][debug][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
2021-03-05T18:00:21.062079971Z stderr F [2021-03-05 18:00:21.061][14][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:247] [C153] new tcp proxy session
2021-03-05T18:00:21.062096471Z stderr F [2021-03-05 18:00:21.061][14][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:395] [C153] Creating connection to cluster server/server
2021-03-05T18:00:21.062101271Z stderr F [2021-03-05 18:00:21.061][14][debug][upstream] [source/common/upstream/original_dst_cluster.cc:45] Using existing host 10.96.201.14:80.
2021-03-05T18:00:21.062105671Z stderr F [2021-03-05 18:00:21.061][14][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
2021-03-05T18:00:21.062109871Z stderr F [2021-03-05 18:00:21.061][14][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C154] connecting
2021-03-05T18:00:21.062114171Z stderr F [2021-03-05 18:00:21.061][14][debug][connection] [source/common/network/connection_impl.cc:860] [C154] connecting to 10.96.201.14:80
2021-03-05T18:00:21.062129271Z stderr F [2021-03-05 18:00:21.061][14][debug][connection] [source/common/network/connection_impl.cc:876] [C154] connection in progress
2021-03-05T18:00:21.062137471Z stderr F [2021-03-05 18:00:21.061][14][debug][pool] [source/common/tcp/original_conn_pool.cc:125] queueing request due to no available connections
2021-03-05T18:00:21.062141471Z stderr F [2021-03-05 18:00:21.061][14][debug][conn_handler] [source/server/connection_handler_impl.cc:501] [C153] new connection
2021-03-05T18:00:21.062145171Z stderr F [2021-03-05 18:00:21.061][14][debug][connection] [source/common/network/connection_impl.cc:666] [C154] connected
2021-03-05T18:00:21.072201363Z stderr F [2021-03-05 18:00:21.062][14][debug][misc] [source/common/network/io_socket_error_impl.cc:30] Unknown error code 104 details Connection reset by peer
2021-03-05T18:00:21.072216563Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:224] [C154] 
2021-03-05T18:00:21.072221263Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:241] [C154] closing socket: 0
2021-03-05T18:00:21.072225163Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:224] [C154] 
2021-03-05T18:00:21.072229163Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C154] client disconnected
2021-03-05T18:00:21.072233263Z stderr F [2021-03-05 18:00:21.062][14][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:395] [C153] Creating connection to cluster server/server
2021-03-05T18:00:21.072250563Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:132] [C153] closing data_to_write=0 type=1
2021-03-05T18:00:21.072255463Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:241] [C153] closing socket: 1
2021-03-05T18:00:21.072259263Z stderr F [2021-03-05 18:00:21.062][14][debug][conn_handler] [source/server/connection_handler_impl.cc:164] [C153] adding to cleanup list
2021-03-05T18:00:21.072264263Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:255] [C154] connection destroyed
```

Server side:
```
2021-03-05T18:00:21.062291271Z stderr F [2021-03-05 18:00:21.061][14][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:79] tls inspector: new connection accepted
2021-03-05T18:00:21.062367971Z stderr F [2021-03-05 18:00:21.061][14][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:150] tls:onServerName(), requestedServerName: server.server.svc.cluster.local
2021-03-05T18:00:21.062373171Z stderr F [2021-03-05 18:00:21.062][14][debug][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
2021-03-05T18:00:21.062378271Z stderr F [2021-03-05 18:00:21.062][14][debug][config] [source/extensions/transport_sockets/tls/ssl_socket.cc:422] Create NotReadySslSocket
2021-03-05T18:00:21.062382971Z stderr F [2021-03-05 18:00:21.062][14][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:247] [C117] new tcp proxy session
2021-03-05T18:00:21.062393071Z stderr F [2021-03-05 18:00:21.062][14][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:395] [C117] Creating connection to cluster server/server-local
2021-03-05T18:00:21.062397371Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:98] creating a new connection
2021-03-05T18:00:21.062402571Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:383] [C118] connecting
2021-03-05T18:00:21.062406171Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:860] [C118] connecting to 0.0.0.0:80
2021-03-05T18:00:21.062410171Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:876] [C118] connection in progress
2021-03-05T18:00:21.062414571Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:125] queueing request due to no available connections
2021-03-05T18:00:21.062418371Z stderr F [2021-03-05 18:00:21.062][14][debug][conn_handler] [source/server/connection_handler_impl.cc:501] [C117] new connection
2021-03-05T18:00:21.062422071Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:241] [C117] closing socket: 0
2021-03-05T18:00:21.062425671Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:223] canceling pending request
2021-03-05T18:00:21.062429271Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:231] canceling pending connection
2021-03-05T18:00:21.062433071Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:132] [C118] closing data_to_write=0 type=1
2021-03-05T18:00:21.062436771Z stderr F [2021-03-05 18:00:21.062][14][debug][connection] [source/common/network/connection_impl.cc:241] [C118] closing socket: 1
2021-03-05T18:00:21.062440171Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:140] [C118] client disconnected
2021-03-05T18:00:21.062443371Z stderr F [2021-03-05 18:00:21.062][14][debug][conn_handler] [source/server/connection_handler_impl.cc:164] [C117] adding to cleanup list
2021-03-05T18:00:21.062446971Z stderr F [2021-03-05 18:00:21.062][14][debug][pool] [source/common/tcp/original_conn_pool.cc:255] [C118] connection destroyed

```

- Dataplane/SMI       [X]

**Environment**:
- OSM version (use `osm version`): main (3/5/2021)
- Kubernetes version (use `kubectl version`): 1.18

**Comment by eduser25** [comment]
Corrected summary, not TCP related. Found by @shashankram :)

**Comment by shashankram** [comment]
The failures in the CI seem to be due to some sort of a race in osm-controller resulting in the SDS config not being realized. In all the failures I have looked at, the SSL socket is not ready.
```
2021-03-05T17:59:18.703510532Z stderr F [2021-03-05 17:59:18.702][14][debug][config] [source/extensions/transport_sockets/tls/ssl_socket.cc:422] Create NotReadySslSocket
```

```
ENVOY_LOG(debug, "Create NotReadySslSocket");
stats_.upstream_context_secrets_not_ready_.inc();
```

This indicates the secrets haven't been pushed, or they aren't warmed in Envoy.

**Comment by draychev** [comment]
Another symptom of this (most likely) bug is the presence of `dynamic_warming_secrets` or generally `warming` in the Envoy config.

This script uses `osm` and `kubectl` CLIs to search for `warm` in Envoy configs:
```bash
#!/bin/bash

for ns in $(kubectl get namespaces --no-headers | awk '{print $1}' | grep -Ev '^kube-'); do
    for pod in $(kubectl get pods -n $ns --no-headers | grep Running | cut -d' ' -f1); do
        echo -e "Checking $ns/$pod"
        ./osm proxy get config_dump -n $ns $pod | grep warm || true
    done
done
```

Relevant PRs:
  - [ ] envoy/ads: program upsteam's service cert when making all secrets #2939
  - [ ] xds: handle wildcard TypeURI #2938
  - [ ] pkg/ticker: reintroduce ticker concept #2937

**Comment by shashankram** [comment]
> Another symptom of this (most likely) bug is the presence of `dynamic_warming_secrets` or generally `warming` in the Envoy config.
> 
> This script uses `osm` and `kubectl` CLIs to search for `warm` in Envoy configs:
> 
> ```shell
> #!/bin/bash
> 
> for ns in $(kubectl get namespaces --no-headers | awk '{print $1}' | grep -Ev '^kube-'); do
>     for pod in $(kubectl get pods -n $ns --no-headers | grep Running | cut -d' ' -f1); do
>         echo -e "Checking $ns/$pod"
>         ./osm proxy get config_dump -n $ns $pod | grep warm || true
>     done
> done
> ```
> 
> Relevant PRs:
> 
> * [ ]  envoy/ads: program upsteam's service cert when making all secrets #2939
> * [ ]  xds: handle wildcard TypeURI #2938
> * [ ]  pkg/ticker: reintroduce ticker concept #2937
> 
> This bug manifested itself while troubleshooting issue #2930
> 
> I have been able to repro more often than not with the following demo script: https://gist.github.com/draychev/787e2b9f63e99dba0f0290351825f89c
> 
> > Note: remove the `readinessProbe`, which may mask the bug

@draychev the secrets might initially be in warming state, but should eventually transition to active. Would you mind augmenting your script to keep polling for a certain duration instead to check if they ever transition from warming to active?

```
$ osm proxy get config_dump azure-vote-front-78dc4ff55b-w5jn4 -n test | grep -A 2 warming
     "warming_state": {
      "version_info": "2",
      "listener": {
--
     "warming_state": {
      "version_info": "2",
      "listener": {
--
     "warming_state": {
      "version_info": "2",
      "listener": {
--
   "dynamic_warming_secrets": [
    {
     "name": "root-cert-for-mtls-inbound:test/azure-vote-front",
$ osm proxy get config_dump azure-vote-front-78dc4ff55b-w5jn4 -n test | grep -A 2 warming
$ osm proxy get config_dump azure-vote-front-78dc4ff55b-w5jn4 -n test | grep -A 2 warming
```

**Comment by shashankram** [comment]
There were multiple issues, some of which have been addressed.

- [X] SDS secrets not being pushed correctly
- [X] SDS assumption regarding service and service account names
- [ ] XDS state machine dropping requests with the same version but newer subscriptions
