### ISSUE TITLE
Milestone v0.10.0 planning

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2800]
This GitHub issue is to be used for planning Open Service Mesh release v0.10.0

---

Previous planning:  **Milestone v0.9.0 planning** #2611

**Comment by draychev** [comment]
Proposed Issues for v0.10

#2768

**Comment by draychev** [comment]
Delyan's proposal for v0.10

Grouped by Theme:

### Retry
- [ ] **(root) retries: Create a Proof-of-Concept for OSM Retry feature** #3338 
  - [ ] retries: Read annotations from TrafficTarget SMI policy #3339
  - [ ] retries: Propagate Retry Policy Config to Envoy proxies #3340
  - [ ] retries: Create minimal demo of the Retry feature #3341

### MeshConfig
- [ ] **Update OSM Demo to accommodate MeshConfig changes.** #3280

### MeshCatalog Cleanup
- [ ] **Move GetServicesForProxy out of MeshCatalog and into Proxy Registry / Proxy{}** #3272
- [ ] **Event-driven Pre-computation of Services per Envoy/Pod** #3273

- [ ] Make certificate key bit size configurable #1933
- [ ] Update the status of the MeshConfig CRD w/ relevant info #3217
- [ ] Update SMI policy's status field w/ errors #3218
- [ ] identity: Make UnmarshalK8sServiceAccount a method on SDSCert and deprecate as a standalone function #3220
- [ ] Simplify kubernetes PubSub API #3174 
- [ ] Configure e2es to run on OpenShift #3097
- [ ] dispatcher: isDeltaUpdate needs more robust implementation #3162 
- [ ] Consolidate metric/scrapping configuration #3065 
- [ ] xds: Envoys should be grouped by ServiceAccount (config distributed should be the same) #3046 
- [ ] doc: Per Service Filter Chains #2858 
- [ ] Add support for linux/arm64 #2821 
- [ ] Use go-control-plane's NewServer() and SnapshotCache system to improve ADS #2683 
- [ ] Required resource setting for injected containers #2472 
- [ ] Create soak test environment for project #2392 
- [ ] Integrate OSM with OPA envoy plugin #1874 
- [ ] Improve test coverage (goal: 80%) #1489
- [ ] cli: Create CLI tool to run troubleshooting tooling #2879 
- [ ] (root) Upgrade story (v2) #3019 
- [ ] envoy: Implement locality-based prioritized (affinitized) endpoint traffic routing #3043
- [ ] envoy: Implement active health checking #3042 
- [ ] cli: Create CLI tool to run troubleshooting tooling #2879 
- [ ] Certificate rotor rotates the same certificate multiple times in the same rotation cycle if the service cert validity duration is <= 1 minute #2832 
- [ ] Add support for linux/arm64 #2821 
- [ ] Allow splitting traffic to same FQDN using multiple traffic split policies matching different routes #2759 
- [ ] Make bookstore app ports configurable in automated demo #2755 
- [ ] Don't expose envoy log level to end users #2754 
- [ ] (root) Use a CRD instead of ConfigMap for OSM configuration #2738 
- [ ] handle traffic split in permissive mode #2527 
- [ ] Use go-control-plane's NewServer() and SnapshotCache system to improve ADS #2683 
- [ ] tool to check envoy config #2728 
- [ ] tool to check for DNS resolution from meshed Pod #2729 
- [ ] SMI conversion webhook to upgrade to newer SMI API versions #2737 
- [ ] (root) Use a CRD instead of ConfigMap for OSM configuration #2738 
- [ ] Make bookstore app ports configurable in automated demo #2755 
- [ ] handle traffic split in permissive mode #2527 
- [ ] Implement custom metrics for all TCP traffic #2506 
- [ ] Aggregated metrics for consumption by Azure monitor and Traffic metrics team #2498 
- [ ] Record expected proxy without relying on in-memory state shared between controller and injector #2481 
- [ ] Root Certificate locality (country, locality, organization) should be configurable (vs const) #2470 
- [ ] Add SMI Traffic Split (v1alpha4) support in the routes v2 feature #2368 
- [ ] OSM CLI prompt to upgrade #2294 
- [ ] Provide Windows container support #2082 
- [ ] Implement distributed tracing w/ Jaeger and Envoy header forwarding #1921 
- [ ] Integrate OSM with OPA envoy plugin #1874 
- [ ] Observability: Integration with AZure monitor #1511 
- [ ] osm command for verifying mTLS connection between two services #1388 
- [ ] expose osm-controller version #1152 
- [ ] Create a demo for an A/B testing example #737 
- [ ] (root) Ingress story for OSM #285 
- [ ] Create an osm command that allows a user to check if an osm control plane is healthy #85 
- [ ] xds: Envoys should be grouped by ServiceAccount (config distributed should be the same) #3046 
- [ ] investigate smi-controller-sdk for osm project #3063

**Comment by shashankram** [comment]
My proposal:

GA readiness:
High availability https://github.com/openservicemesh/osm/issues/3390
Envoy health check: https://github.com/openservicemesh/osm/issues/3042
Better logging: https://github.com/openservicemesh/osm/issues/2924
Envoy log: https://github.com/openservicemesh/osm/issues/2754
Ingress security hardening: https://github.com/openservicemesh/osm/issues/2365

Upstream usability:
CLI/doc compatibility: https://github.com/openservicemesh/osm/issues/3371
Grafana licensing implications: https://github.com/openservicemesh/osm/issues/3208
Document k8s version skew: https://github.com/openservicemesh/osm/issues/2852
Security disclosure process: https://github.com/openservicemesh/osm/issues/2402
CLI upgrade prompt: https://github.com/openservicemesh/osm/issues/2294

Troubleshooting:
CLI tools: https://github.com/openservicemesh/osm/issues/2879
Error visibility: https://github.com/openservicemesh/osm/issues/2866
Consistency check tool: https://github.com/openservicemesh/osm/issues/2099
Debug sidecar: https://github.com/openservicemesh/osm/issues/682
Control plane health: https://github.com/openservicemesh/osm/issues/85

Upgrade:
https://github.com/openservicemesh/osm/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fupgrade (except #512 )

Identity:
https://github.com/openservicemesh/osm/issues/3187
https://github.com/openservicemesh/osm/issues/3188
https://github.com/openservicemesh/osm/issues/3186
https://github.com/openservicemesh/osm/issues/3182

Observability:
https://github.com/openservicemesh/osm/issues/3164
https://github.com/openservicemesh/osm/issues/3065
https://github.com/openservicemesh/osm/issues/2506
https://github.com/openservicemesh/osm/issues/2408
https://github.com/openservicemesh/osm/issues/1921
Ingress metrics: https://github.com/openservicemesh/osm/issues/1697

SMI:
Traffic split v1alpha4 https://github.com/openservicemesh/osm/issues/2368
Flagger: https://github.com/openservicemesh/osm/issues/1700

All bugs:
https://github.com/openservicemesh/osm/issues?q=is%3Aissue+is%3Aopen+label%3Abug

**Comment by snehachhabria** [comment]
We should add some work items on multicluster features, issues for these are work in progress from my end

**Comment by michelleN** [comment]
- [ ] Implement SMI Metrics API Server https://github.com/openservicemesh/osm/issues/1540
- [ ] Build OSM/Flagger demo https://github.com/openservicemesh/osm/issues/1700
- [ ] TrafficSplit v1alpha4 https://github.com/openservicemesh/osm/issues/2368
- [ ] Handling existing policies after SMI crd upgrade https://github.com/openservicemesh/osm/issues/893
- [ ] https://github.com/openservicemesh/osm/issues/3063
