### ISSUE TITLE
(root) Ingress story for OSM

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#285]
This is the top level GitHub issue for a) designing b) implementing of a complete Ingress story for Open Service Mesh, which includes:
  - [ ] HTTP traffic to backend Pods
  - [ ] HTTPS (mTLS and TLS)

---
Related Issues:

- [x] #3501
- [x] #2365
- [x] #3700
- [ ] #1697
- [x] #1020
- [ ] #981

**Comment by draychev** [comment]
Reopening this to continue to track OSM's Ingress Story.

**Comment by draychev** [comment]
Related issues:
  - [ ] doc: Ingress #2871
  - [ ] Document how to install ngnix ingress controller #2827
  - [ ] doc: Integrate w/ AGIC #2868
  - [ ] Ingress with ngnix results in 502 bad gateway #2930

**Comment by michelleN** [comment]
tested and demo'ed. Thank you!
