### ISSUE TITLE
Label all OSM deployed Kubernetes resources with a common key/value

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2925]
This issue is for the creation of a Kubernetes label (key/value pair), which will be applied to all Kubernetes resources created by the `osm` CLI or the OSM Control  plane.

For troubleshooting purposes it would be great to have a single command, which can list all OSM-related Kubernetes resources.

We can use:
```bash
kubectl get all -A --selector app=osm-controller
```
The current output of this command is:

```
$ kubectl get all -A --selector app=osm-controller

NAMESPACE    NAME                                  READY   STATUS    RESTARTS   AGE
osm-system   pod/osm-controller-545cbd8b68-98hgs   1/1     Running   0          5m22s

NAMESPACE    NAME                           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
osm-system   service/osm-config-validator   ClusterIP   11.1.111.111   <none>        9093/TCP             5m22s
osm-system   service/osm-controller         ClusterIP   11.0.111.112   <none>        15128/TCP,9092/TCP   5m22s

NAMESPACE    NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
osm-system   deployment.apps/osm-controller   1/1     1            1           5m22s

NAMESPACE    NAME                                        DESIRED   CURRENT   READY   AGE
osm-system   replicaset.apps/osm-controller-545cbd8b68   1         1         1       5m22s
```

The `osm-system/osm-config` ConfigMap does not appear on that list because it is not labeled with `app=osm-controller`.
Same for Validating and Mutating WebhookConfigurations.

The label we could us should be something a bit more generic than `app=osm-controller` since this would be applied to all resources. Perhaps `app=openservicemesh.io`?

This will be used in https://github.com/openservicemesh/osm/issues/2926

ref #2920

**Comment by michelleN** [comment]
Here are some best practices on labels from Kubernetes:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/


I'd recommend we use something like `app.kubernetes.io/name=osm` or `openservicemesh.io/mesh-name=<mesh-name>`

**Comment by draychev** [comment]
Thanks @michelleN - k8s common labels is great.

Re-using the example and ideating around what these could look like
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: openservicemesh
    app.kubernetes.io/instance: openservicemesh-specifc-name-of-mesh-instance   # This could be the unique name of the mash, but so could "part-of"
    app.kubernetes.io/version: v0.8.0    # OSM Release Version (CLI + Controller)
    app.kubernetes.io/component: injector   # Specific component -- ConfigMap, Injector, Controller, ValidatingWH, MutatingWH, etc
    app.kubernetes.io/part-of: openservicemesh-specific-name-of-mesh-instance   # Is this better suited for the uniq mesh name?
    app.kubernetes.io/managed-by: helm
```

**Comment by draychev** [comment]
The following proposals depend on this task:
  - [ ] Move osm-config ConfigMap ownership from Helm to OSM Controller #2932
  - [ ] Research and build POC for Helm post-delete hook for OSM resources #2931

The following issues depend on the dependent issues/fixes (above):
  - [ ] osm mesh upgrade reverts configmap value changes which were made out of band #2826
  - [ ] helm upgrade overrides manual edits in osm-config #2386

**Comment by draychev** [comment]
@snehachhabria pinging you on this GitHub Issue because I know you have been thinking about this.

**Comment by michelleN** [comment]
Re-labeling to p0 since there are p0 tasks that depend on this. Feel free to change back @draychev

**Comment by draychev** [comment]
@nojnhuh Thank you so much for picking up this task!  Labeling all the assets deployed by OSM in a consistent way would make our lives so much easier!
In an earlier comment I proposed something like that -- just to illustrate the richness of data we can add via labels:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: openservicemesh
    app.kubernetes.io/instance: openservicemesh-specifc-name-of-mesh-instance   # This could be the unique name of the mash, but so could "part-of"
    app.kubernetes.io/version: v0.8.0    # OSM Release Version (CLI + Controller)
    app.kubernetes.io/component: injector   # Specific component -- ConfigMap, Injector, Controller, ValidatingWH, MutatingWH, etc
    app.kubernetes.io/part-of: openservicemesh-specific-name-of-mesh-instance   # Is this better suited for the uniq mesh name?
```
It'd be great to be able to see the version of OSM that installed a component etc.

Thank you!
