### ISSUE TITLE
Milestone v0.8.1 planning

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2928]
This GitHub Issue is for a 1-week spike on tasks we need to get done in the next 7-10 days with (by the end of week of March 21st) and before we release 0.9.

**Comment by draychev** [comment]
- [ ] #2925  -  Label all OSM deployed Kubernetes resources with a common key/value
- [ ] #2103  -  Add runtime config/osm boot flags to configure ticker/resyncs

### Validating Webhook
- [ ] #2819  -  OSM Validating Webhook blocks valid ConfigMap patches post upgrade
- [ ] #2926  -  Use objectSelector in ValidatingWebhookConfigurotion to limit objects observed

**Comment by snehachhabria** [comment]
Should we tackle this issue as well if possible : #2930 ?
