### ISSUE TITLE
Move osm-config ConfigMap ownership from Helm to OSM Controller

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2932]
> **NOTE:** Proposal #2738 may obsolete this GitHub issue

---

This GitHub issue is to propose, discuss, design, and potentially implement a different ownership model for the OSM ConfigMap: `osm-system/osm-config`.

In short:
  1. Remove `osm-config` ConfigMap from Helm charts
  2. Make OSM Controller create, label properly, and ensure `osm-config` always exists

### Why do we need to make this change?
As it was noted in a few bugs - Helm upgrade as of v0.8 overwrites values in the ConfigMap that were added by the OSM user:
  - [ ] #2826 - osm mesh upgrade reverts configmap value changes which were made out of band
  - [ ] #2386 - helm upgrade overrides manual edits in osm-config

A similar proposal is in the comments of one of the bugs: https://github.com/openservicemesh/osm/issues/2386#issuecomment-801671109

### Proposal
A solution to the bugs listed above would be:

1. Remove the `osm-config` ConfigMap from Helm's purview. Helm won't create the ConfigMap, Helm won't overwrite the ConfigMap.
2. Move ConfigMap creation into OSM Controller. OSM Controller can start and function without the `osm-config` ConfigMap.

With this setup the `osm-config` ConfigMap can be changed both via OSM CLI and kubectl. The config map itself will be the source of truth regardless of who modifies it. Helm upgrade will not overwrite it. This solves the requirement to persist the ConfigMap content between upgrades.

We know that a side effect of Helm not installing the ConfigMap is going to be - Helm not cleaning up the ConfigMap on `helm delete`.  I created the following GitHub Issue to research a `post-delete` Helm hook, which can clean up ghost (all) OSM artifacts:
  - [ ] #2931  -  Research and build POC for Helm post-delete hook for OSM resources
 
For the `post-delete` hook to work - we need to have proper labels on all OSM artifacts:
 - [ ] #2925  -  Label all OSM deployed Kubernetes resources with a common key/value

With ownership moved, we can discuss a different UX for `--enable-permissive-traffic-policy`, `--enable-egress` and other ConfigMap related CLI options:
  - [ ] cli: Remove --enable-permissive-traffic-policy from osm install CLI (can we?) #2922

**Comment by draychev** [comment]
Assigning this to @allenlsy, who is working to convert the `osm-config` ConfigMap to a CRD, which will actually deprecate this issue here (#2932)

**Comment by snehachhabria** [comment]
Closing this issue as we will be deprecating the configmap ( #2738 )
