### ISSUE TITLE
(root) Upgrade story (v2)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3019]
This is the root (or top level) GitHub issue for all things related to OSM Upgrade.

---

### Tasks to complete v2 of `osm upgrade`
- [x] Proposal: Use a CRD instead of ConfigMap for OSM configuration #2738
- [x] Label all OSM deployed Kubernetes resources with a common key/value #2925
- [x] ~~SMI conversion webhook to upgrade to newer SMI API versions #2737~~
- [x] ~~osm mesh upgrade reverts configmap value changes which were made out of band #2826~~
- [x] helm upgrade overrides manual edits in osm-config #2386
- [x] Research and build POC for Helm post-delete hook for OSM resources #2931
- [X] ~~Move osm-config ConfigMap ownership from Helm to OSM Controller #2932~~
- [ ] Add check in the OSM CLI for available updates / upgrades / new versions #1720
- [X] ~~How does OSM upgrade handle SMI version upgrades on a cluster with existing policies? #893~~
- [ ] Support hitless upgrade of Envoy proxies #512
- [X] ~~Move osm webhook configuration resource ownership from Helm to OSM Controller #2961~~ 
- [X] ~~ CRD spec change to allow storing older versions of the CRD #3211~~
- [x] Deprecate the use of osm mesh upgrade to update the OSM config #3212
- [X] #3396
- [ ] #3371

### Clean-up tasks for after v2 of `osm upgrade` is done:
- [X] cli: Remove --enable-permissive-traffic-policy from osm install CLI (can we?) #2922
- [X] cli: remove install cli options used for overriding chart values in favor of using --set option #3124 

---

Prior work:
- feat(cli): control plane upgrades #2418
- Make OSM control plane instances upgradeable #2100

**Comment by draychev** [comment]
Done! (Remaining CLI tasks will also be addressed in follow-up release - v0.11)
