### ISSUE TITLE
config: Design a new OSM Config CRD (YAML only)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3033]
This issue is for the creation of a new CRD - `config.openservicemesh.io`

This CRD will be used in lieu of the `osm-system/osm-config` ConfigMap. It will contain the exact same keys.
The ConfigMap keys are documented here:  https://github.com/openservicemesh/osm/blob/v0.8.2/docs/content/docs/osm_config_map.md

And in code: https://github.com/openservicemesh/osm/blob/v0.8.2/pkg/configurator/client.go#L19-L61

Proposal:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: config.openservicemesh.io
spec:
  group: openservicemesh.io
  version: v1
  names:
    kind: Configuration
    plural: configurations
    singular: configuration
  scope: Namespaced
```

The following list of PRs contains sample code on how we have created experimental CRDs in the past: https://github.com/openservicemesh/osm/pulls?q=is%3Apr+backpressure+is%3Aclosed
The following PR contains all files for one particular CRD: https://github.com/openservicemesh/osm/pull/2555

Here is an example of a CRD:  https://github.com/openservicemesh/osm/pull/2555/files#diff-1cafe11315dc6a25640aa8dd8d5532d69abc54580a48f71280aade876c504ccc

---

Next Steps:
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041

**Comment by draychev** [comment]
Completed with #3093 3093
