### ISSUE TITLE
config: Add validation to the new OSM Config CRD (in YAML)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3034]
This issue is for the addition of a `validation` to the config CRD.

For example:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: config.openservicemesh.io
spec:
  group: openservicemesh.io
  version: v1
  names:
    kind: Configuration
    plural: configurations
    singular: configuration
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            egress:
              description: "Enable egres..............."
              type: boolean
            some-other-property:
              description: "...."
              type: integer
              pattern: '^[1-9]{1}[0-9]*'
```
---

This issue is blocked / depends on:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041

**Comment by draychev** [comment]
Completed with #3033
