### ISSUE TITLE
config: Create code gen helper for generation of Go Client code for new OSM Config CRD

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3035]
This issue is for the creation of a new bash tool `scripts/gen-config-crd-client.sh`, which will then be used for the generation of the OSM Configuration CRD Go client code (#3033).

Here is an example of such helper script we have used in the past: https://github.com/openservicemesh/osm/pull/848/files#diff-ca2162e0ab8633745bf12ec8cec553b44e47a9563021b0d30f0d7e9a065fa5ee

This script should be documented and committed to the repo so we can invoke it when we need to refresh the CRD with new fields. (These steps should be documented.)

> Note: the script below was created a long time ago and how it does things may already be obsolete.

```bash
#!/bin/bash

set -auexo pipefail

DIR="$GOPATH/src/k8s.io/"

if [ ! -d "${DIR}code-generator" ]; then
  mkdir -p "$DIR"
  pushd "$DIR"
  git clone git@github.com:kubernetes/code-generator.git
  popd
fi

../code-generator/generate-groups.sh \
    all \
    github.com/open-service-mesh/osm/pkg/client \
    github.com/open-service-mesh/osm/pkg/apis \
    "osmbackpressureconfig:v1" \
    --go-header-file ../code-generator/hack/boilerplate.go.txt
```

---

This issue is blocked / depends on:
  - [x] config: Add validation to the new OSM Config CRD (in YAML) #3034

---

All related issues:
  - [x] config: Design a new OSM Config CRD (YAML only) #3033
  - [x] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [x] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041
