### ISSUE TITLE
config: Generate Go Client code for new OSM Config CRD

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3037]
This issue is for the generation of the Go client code for the newly created OSM Configuration CRD (#3033)

With #3035 we created a bash script helper, which generates the code based on the YAML created with #3033 and #3034. This issue here is for the addition of the generated code to the OSM repo.

Example of generated code:  https://github.com/openservicemesh/osm/pull/933/files

(There is a lot of it - it would be great to commit it in one PR where the PR contains only the auto-generated code)

---

This issue is blocked / depends on:
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041
