### ISSUE TITLE
config: Create new Configuration CRD informers

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3038]
This issue is for the creation of informers for the new Configuration CRD.
The goal of this is to create them and merge them to main without breaking the existing ConfigMap-based configuration.

The informers should emit logs when they notice changes to the CRD, which would allow us to validate the entire system so far - from the creation of a versioned CRD with certain keys and values - all the way through to these keys/values appearing in the OSM Controller.

An example of where we implemented custom resource definition informers for OSM: https://github.com/openservicemesh/osm/pull/1022/files

---

This issue is blocked / depends on:
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041
