### ISSUE TITLE
config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3039]
This is the final task from the config series. This issue is for the removal of the Configmap and using instead the Config CRD in the `pkg/configurator` module:

Where the `osm-system/osm-config` ConfigMap is used: https://github.com/openservicemesh/osm/blob/main/pkg/configurator/client.go#L94-L101

---

This issue is blocked / depends on:
  - [ ] config: Create new Configuration CRD informers #3038

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041

**Comment by snehachhabria** [comment]
all the code changes for this have been checked in, cleanup will be handled with issue #3040
