### ISSUE TITLE
config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3040]
This issue is for updating all documentation where we reference the ConfigMap `osm-system/osm-config`.
Also remove all references to this config map in comments/code/docs etc.

---

This issue is blocked / depends on:
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039

---

All related issues:
  - [ ] config: Design a new OSM Config CRD (YAML only) #3033
  - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
  - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
  - [ ] config: Generate Go Client code for new OSM Config CRD #3037
  - [ ] config: Create new Configuration CRD informers #3038
  - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
  - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040
  - [ ] config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes) #3041

**Comment by snehachhabria** [comment]
Part of the doc update has been addressed with this PR : https://github.com/openservicemesh/osm-docs/pull/27

**Comment by bridgetkromhout** [comment]
ConfigMap references in the docs repo include:
https://github.com/openservicemesh/osm-docs/blame/main/content/docs/install/_index.md#L68
https://github.com/openservicemesh/osm-docs/blame/main/content/docs/install/_index.md#L94
https://github.com/openservicemesh/osm-docs/blob/main/content/docs/troubleshooting/osm_configmap.md

and more instances.

**Comment by snehachhabria** [comment]
> ConfigMap references in the docs repo include:
> https://github.com/openservicemesh/osm-docs/blame/main/content/docs/install/_index.md#L68
> https://github.com/openservicemesh/osm-docs/blame/main/content/docs/install/_index.md#L94
> https://github.com/openservicemesh/osm-docs/blob/main/content/docs/troubleshooting/osm_configmap.md
> 
> and more instances.

Thanks @bridgetkromhout , I am in the process of preparing a PR for all the changes in the docs repo, I will make sure to address these

**Comment by snehachhabria** [comment]
all the docs have been updated with this PR : https://github.com/openservicemesh/osm-docs/pull/43 . The only pending item is to create a doc similar to this : https://github.com/openservicemesh/osm-docs/blob/main/content/docs/apidocs/policy/v1alpha1.md for the meshconfig

**Comment by bridgetkromhout** [comment]
Thanks. I commented in https://github.com/openservicemesh/osm-docs/pull/43/files#r632861480.

**Comment by snehachhabria** [comment]
All docs related to meshConfig have been updated with these two PRs : https://github.com/openservicemesh/osm-docs/pull/55 and https://github.com/openservicemesh/osm-docs/pull/53
