### ISSUE TITLE
config: Update ValidatingWebhookConfig and handler (for osm-config ConfigMap changes)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3041]
This task is for updating (or completely removing) the `ValidatingWebhookConfiguration` for `osm-system/osm-config` ConfigMap changes.

After we complete all tasks listed below we will **not** have a `osm-system/osm-config` ConfigMap. There will be no need to have a ValidatingWebhookConfiguration. The validation will happen within the CRD itself.

The ValidatingWebhookConfiguration can (most likely) be deleted.

---

Related tasks:

  - [ ] Proposal: Use a CRD instead of ConfigMap for OSM configuration #2738 
    - [ ] config: Design a new OSM Config CRD (YAML only) #3033
    - [ ] config: Add validation to the new OSM Config CRD (in YAML) #3034
    - [ ] config: Create code gen helper for generation of Go Client code for new OSM Config CRD #3035
    - [ ] config: Generate Go Client code for new OSM Config CRD #3037
    - [ ] config: Create new Configuration CRD informers #3038
    - [ ] config: Swap ConfigMap usage with Configuration CRD in the pkg/configurator module #3039
    - [ ] config: Update documentation to reflect the usage of a Configuration CRD (not a ConfigMap); Cleanup #3040

**Comment by snehachhabria** [comment]
we will no longer need a validating webhook, the crd has validations. The validating webhook code can be deleted from osm

**Comment by allenlsy** [comment]
Issue resolved
