### ISSUE TITLE
[RFC] Clean up of MeshCataloger interface

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3111]
This GitHub Issue is for the exploration and design of a new cleaner MeshCataloger interface.

- Started: 2021-04-08
- Current Status: Research & Gathering Feedback phase

--

# Ongoing Changes
These are PRs and issues that are meant to be merged (fixed) and will improve the mesh catalog interface:
- [x] Pull releaseCertificateHandler out of Mesh Catalog into a separate package #3106
- [x] RFC: Split Proxy Registry from Mesh Catalog interface (removes RegisterProxy, UnregisterProxy, ExpectProxy) #3105
- [x] Removing ListSMIPolicies() and ListMonitoredNamespaces() from MeshCataloger interface #3109
- [x] catalog: delete interface function ListMonitoredNamespaces() #3084
- [x] catalog: Remove GetServicesForServiceAccount from MeshCataloger interface #3115
- [x] catalog: Remove ListEndpointsForService from MeshCataloger interface #3113
- [ ] Use ServiceIdentity type in catalog APIs instead of service.K8sServiceAccount #2218
- [x] catalog: Rename GetServicesFromEnvoyCertificate to GetServicesForProxy #3117
- [x] Remove GetSMISpec() from MeshCataloger interface #3148 
- [x] catalog: Remove GetServicesFromEnvoyCertificate from MeshCataloger interface #3149

---

# Explorations:
These are incomplete (unmergeable) PRs showing possible refactors and clean-ups:
- [ ] [RFC] catalog: Remove ListServiceAccountsForService and add GetServiceAccountsForCert to MeshCataloger interface #3112

---

# Other Related Proposals:
- [ ] [RFC] Proposal to move most types used by mesh catalog into pkg/catalog #3116

---

# Potential cleaned-up interface
After all changes (above) are applied we could end up with the following:
```go
type MeshCataloger interface {
	ListInboundTrafficPolicies(service.K8sServiceAccount, []service.MeshService) []*trafficpolicy.InboundTrafficPolicy
	ListOutboundTrafficPolicies(service.K8sServiceAccount) []*trafficpolicy.OutboundTrafficPolicy
	ListAllowedOutboundServicesForIdentity(service.K8sServiceAccount) []service.MeshService
	ListAllowedInboundServiceAccounts(service.K8sServiceAccount) ([]service.K8sServiceAccount, error)
	ListAllowedOutboundServiceAccounts(service.K8sServiceAccount) ([]service.K8sServiceAccount, error)
	ListAllowedEndpointsForService(service.K8sServiceAccount, service.MeshService) ([]endpoint.Endpoint, error)
	GetResolvableServiceEndpoints(service.MeshService) ([]endpoint.Endpoint, error)
	GetIngressPoliciesForService(service.MeshService) ([]*trafficpolicy.InboundTrafficPolicy, error)
	GetTargetPortToProtocolMappingForService(service.MeshService) (map[uint32]string, error)
	GetPortToProtocolMappingForService(service.MeshService) (map[uint32]string, error)
	ListInboundTrafficTargetsWithRoutes(service.K8sServiceAccount) ([]trafficpolicy.TrafficTargetWithRoutes, error)

	ListMeshServiceForServiceAccount
	GetWeightedClustersForUpstream
	GetServiceAccountsForCert 
}
```
### Added
 - `ListMeshServiceForServiceAccount`
 - `GetWeightedClustersForUpstream`
 - `GetServiceAccountsForCert`

### Removed
 - `GetSMISpec() smi.MeshSpec`
 - `ListServiceAccountsForService(service.MeshService) ([]service.K8sServiceAccount, error)`
 - `ListEndpointsForService(service.MeshService) ([]endpoint.Endpoint, error)`
 - `GetServicesFromEnvoyCertificate(certificate.CommonName) ([]service.MeshService, error)`
 - `GetServicesForServiceAccount(service.K8sServiceAccount) ([]service.MeshService, error)`
 - `ListMonitoredNamespaces() []string`
 - `ListSMIPolicies() ([]*split.TrafficSplit, []service.K8sServiceAccount, []*spec.HTTPRouteGroup, []*access.TrafficTarget)`
 - `RegisterProxy(*envoy.Proxy)`
 - `UnregisterProxy(*envoy.Proxy)`
 - `ExpectProxy(certificate.CommonName)`
