### ISSUE TITLE
(root) Certificates

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3242]
This GitHub Issue is to aggregate all other work around certificates:

- [ ] Documentation [doc: Certificates and Rotation #2860](https://github.com/openservicemesh/osm/issues/2860) 
- [ ] [Root Cert Rotation Story #1260](https://github.com/openservicemesh/osm/issues/1260)
- [ ] [Make certificate key bit size configurable #1933](https://github.com/openservicemesh/osm/issues/1933)
- [ ] [Provide custom expiration for the internal OSM CA / root cert #3241](https://github.com/openservicemesh/osm/issues/3241)

**Comment by snehachhabria** [comment]
closing this root issue as there will be a new issue to track certificate rotation
