### ISSUE TITLE
(root) Multicluster OSM

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3456]
With [Multicluster OSM design doc](https://docs.google.com/document/d/1O3XcG27uryBxCHX719qYUUzAo913GoFv3LOwdnfNudQ/edit#) we proposed an MVP solution, which enables a particular multicluster scenario.

The following GitHub issues take the next steps in implementing this proposal:

- [ ] CI environment for multicluster #3452
- [ ] Orchestration for osm multicluster #3449
- [ ] CoreDNS plugin for OSM in Multicluster mode #3447
- [ ] certificate management for multicluster #3446
- [X] OSM Controller changes to support multicluster mode #3444
- [ ] Resolve multicluster gateway IP #3441
- [X] Create a multicluster gateway #3440
- [X] Create OSM multicluster CRD #3403
- [x] Create a feature flag for OSM multicluster #3402
- [ ] identity: Remove hard-coded cluster.local trust domain and make flexible #3187
- [ ] envoy: Implement locality-based prioritized (affinitized) endpoint traffic routing #3043
- [ ] Build a proof of concept of the idea locality-based routing using Envoy #3557
- [ ] Use an intermediate certificate to sign all service-to-service mTLS certs #507
- [ ] multicluster: Add support for Azure-Arc #2111

**Comment by howardjohn** [comment]
Hey, I was taking a look at https://docs.google.com/document/d/1O3XcG27uryBxCHX719qYUUzAo913GoFv3LOwdnfNudQ/ and wanted to mention the https://github.com/kubernetes-sigs/mcs-api/ APIs that are being introduced by the sig-multicluster team.

The project aims to solve many of the same problems discussed in the design doc here, but is a standardized API that is implemented by a few (hopefully more soon!) other projects. Have you had a chance to take a look at this and see if it meets your needs? If there are gaps I am sure sig-multicluster would appreciate to hear them and possibly work together with your team to make sure it can meet your requirements.

**Comment by draychev** [comment]
@howardjohn Thanks for the pointer! I'll a look at MCS API again and will join the meetups (have been meaning to)!
It'd be great to leverage the MCS API as these approach graduation!

**Comment by marcindulak** [comment]
:eyes:

**Comment by marcindulak** [comment]
:eyes:

**Comment by marcindulak** [comment]
:eyes:
