### ISSUE TITLE
v0.8 documentation

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3470]
This GitHub issue is the root node for all tasks related to creating a) Documentation b) Demo scenarios c) Troubleshooting Guides w/ common issues for v0.8 of OSM

## Immediate documentation needs for v0.8
  - [x] Permissive Traffic Mode: openservicemesh/osm-docs#81 
  - [x] TCP Route + OSM handling TCP traffic: openservicemesh/osm-docs#80 
  - [x] Traffic Split: openservicemesh/osm-docs#79 (ensure existing docs are 💯)
  - [ ] per-service Filter Chains: openservicemesh/osm#2858
  - [x] Certificates and Rotation: openservicemesh/osm-docs#78
  - [x] Table w/ SMI versions supported by v0.8: openservicemesh/osm#2862
  - [x] Integrate w/ Nginx: openservicemesh/osm#2827
  - [x] Integrate w/ AGIC: openservicemesh/osm-docs#75
  - [x] Remove references to onboarding VMs: openservicemesh/osm#2863
  - [x] Egress: openservicemesh/osm-docs#77
  - [x] Ingress: openservicemesh/osm-docs#76
  - [x] Integrate w/ Grafana: openservicemesh/osm#2873
  - [x] Integrate w/ Prometheus: openservicemesh/osm#2874
  - [x] Integrate w/ Dapr: openservicemesh/osm#2875
  - [x] Payload Health Probes openservicemesh/osm#2876
  - [x] OSM Controller health probes openservicemesh/osm#2877
  - [x] Uninstalling OSM: openservicemesh/osm#2880
  - [x] Integration w/ Jaeger openservicemesh/osm#2881
  - [x] Integrate w/ Azure Monitor openservicemesh/osm-docs#74
  - [x] Caveats and peculiarities of container startup sequencing: openservicemesh/osm-docs#73
  - [x] Dynamic iptables configuration: openservicemesh/osm-docs#72
  - [x] `osm-config` ConfigMap openservicemesh/osm#2886
  - [x] Update Scale and limits: openservicemesh/osm#2893
  - [x] Document how "osm namespace join" works: openservicemesh/osm#2904
  - [x] Document support for different application traffic types openservicemesh/osm-docs#82

[Link to the list of issues (`documentation` + `p0`)](https://github.com/openservicemesh/osm/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation+label%3Ap0+)

### Longer Term
  - [ ] Adding unique error codes to Error messages: openservicemesh/osm#2866
  - [ ] Summary and links to all demos on front-page: openservicemesh/osm#2872
  - [ ] Create CLI tool to run troubleshooting tooling: openservicemesh/osm#2879

### Related / Follow-up
  - [ ] Update release guide to point docs w/ hardcoded OSM versions: openservicemesh/osm#2908
  - [x] Move and reorganize all newly written docs for v0.8: openservicemesh/osm-docs#83

**Comment by bridgetkromhout** [comment]
I'm moving this issue back to the code repo now that we have other issues for all the checked-off items, so it can be revisited and handled in terms of demos/examples that remain.

**Comment by shashankram** [comment]
v0.8 docs are archived and are no longer being updated.
