### ISSUE TITLE
Integrate with Azure Key Vault

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#4501]
**Please describe the Improvement and/or Feature Request**
Integrate OSM with Azure Key vault : https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts

The tasks include:
- [ ] Research how AKV can be used with OSM
- [ ] Design doc (a Google doc linked to this item)
- [ ] Implementation
- [ ] Unit and e2e tests
- [ ] Documentation: how-to guide
- [ ] Documentation: demo

**Scope (please mark with X where applicable)**
- New Functionality          [X]

**Comment by steeling** [comment]
Looking at the code base, I've identified some refactoring opportunities prior to adding a new cert manager:

- [ ] [Remove certificate.Certificater](https://github.com/openservicemesh/osm/issues/4532)
- [ ] [Leverage a new certificate.Administrator type](https://github.com/openservicemesh/osm/issues/4533)
- [ ] [Switch to options interface, remove provider.Config, factory-style code](https://github.com/openservicemesh/osm/issues/4534)

**Comment by steeling** [comment]
closing this for now, as the recommendation would be to use cert-manager or CSI driver
