### ISSUE TITLE
[Root] OSM performance and scalability test in v1.2

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#4622]
**Please describe the Improvement and/or Feature Request**

This is the root Github issue for tracking the progress and plan of OSM performance benchmarking and scalability test at the release of v1.2. The scripts o the test resides in the [osm-perftest](https://github.com/openservicemesh/osm-perftest) repo.

### Setup & Automation

- [x] [load generator send requests to multiple endpoints](https://github.com/openservicemesh/osm-perftest/issues/28)
- [x] [[load generator] support setting replicas](https://github.com/openservicemesh/osm-perftest/issues/27)
- [x] [Gather Envoy metrics](https://github.com/openservicemesh/osm-perftest/issues/18)
- [x] [Gather full test reports with one click](https://github.com/openservicemesh/osm-perftest/issues/7)
- [x] [Run the same perf test scenario using other service mesh products.](https://github.com/openservicemesh/osm-perftest/issues/42)

### Performance

- [x] [Profiling OSM control plane performance](https://github.com/openservicemesh/osm-perftest/issues/31)
- [ ] [[WIP PR](https://github.com/openservicemesh/osm-docs/pull/367)] [Data plane performance change with number of connections](https://github.com/openservicemesh/osm/issues/2993)

### Scalability

- [ ] [ [WIP PR](https://github.com/openservicemesh/osm-docs/pull/367) ] [Additional scalability testing scenarios](https://github.com/openservicemesh/osm-perftest/issues/34)

### Profiling

- [x] Offline profiling: benchmark key process performance
- [x] [Document online profiling setup and process](https://github.com/openservicemesh/osm/issues/4694) [ [PR](https://github.com/openservicemesh/osm/pull/4744) ] 
- [x] Online profiling process

**Comment by allenlsy** [comment]
@trstringer feel free to assign this task to me. I plan to work on this in Q2.
