### ISSUE TITLE
Implement troubleshooting tooling within OSM CLI

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4634]
**Please describe the Improvement and/or Feature Request**
Implement a troubleshooting tool within OSM CLI to detect, verify, and troubleshoot the correctness of the system for various scenarios.

Previously, a proof-of-concept for this was built as a part of the [osm-health](https://github.com/openservicemesh/osm-health) project. However, there are several limitations with osm-health and it needs to be heavily refactored to be usable, for the following reasons:
1. osm-health was developed independently outside the core osm project repo. The code and design have not been reviewed by all the required stakeholders of the osm projects, and there is a disconnect in terms of how we currently expect the troubleshooting tool to operate. Some of these are highlighted below.
2. Many of the checks implemented within osm-health make assumptions that should not be made, e.g. regarding traffic type (HTTP, TCP, etc.), image tags, error logs, etc. As a result, the tool is unusable beyond a very narrow scenario which makes it unusable in production environments.
3. The tool runs a k8s controller (informer + caches) which is completely unnecessary. Simple API calls via client-go should suffice. Running a k8s controller makes the code more complex than necessary.
4. The output on the console is not concise. Given the use of k8s controller within the tool, control plane logs are emitted with commands. While this can be suppressed, it's best to write to stdout/stderr in a console-friendly manner as common with CLIs.
5. Having the tool within osm CLI simplifies the development, testing, and release workflows.
6. Single tool for OSM management and troubleshooting - OSM CLI

I am proposing to reimplement the necessary tooling as a part of OSM CLI while borrowing certain ideas from osm-health. Integrating this tooling into OSM CLI also gives us the opportunity to think about the structure of the tooling project in code versus simply retrofitting the osm-health POC, which uses a directory structure not suitable within the osm repo, into the core osm repo.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- CLI Tool                   [X]

**Possible use cases**
Troubleshooting tool for OSM.

**Tasks**
- [x] Pod-to-pod connectivity configuration verification
- [x] Pod-to-external (egress) connectivity configuration verification
- [x] External-to-pod (ingress) connectivity configuration verification
- [x] Control plane health

**Comment by steeling** [comment]
I have some thoughts in this area, but don't have the time on my plate currently. This seems large enough scope to warrant a small design doc prior to moving forward with implementation

**Comment by steeling** [comment]
Yup! I see 3 ways to get data to inspect:

1. Open a port-forward session to a sidecar and get a config dump
2. Open a port-forward session to a (new) gRPC server on the osm-controller that has a defined service for interpreting various commands.
3. Open a port-forward session to the sidecar-wrapper (this doesn't exist yet, but future designs are going to require a custom image that has some other processes running in the sidecar instead of vanilla envoy), that may know how to interpret some commands -- Not advocating for this yet, and we should probably hold off, or only enable with a flag being set on the mesh config.
4. Querying the k8s api directly and inspecting k8s objects (including status).
5. Creating a new Adding a new `osm-debugger` pod that can be turned up on demand that has nmap, curl, wget, nslookup etc, so users can exec into the pod, and run commands. The cli command can take multiple flags, to turn up the pod in different forms, ie: `--in-mesh --connect-to=$identity`, or `--out-of-mesh, --connect-to-all` may create the appropriate ingress backends, sidecar configs etc. It can also have a gRPC server running that can accept commands and try to detect connectivity problems.

I think it's also worth calling out exactly which scenarios we intend to provide a command to inspect/healthcheck. ie: Lack of connectivity on ingress due to misconfigured certs, misconfigred XYZ, or missing traffic policy for $service, etc

**Comment by shashankram** [comment]
> Yup! I see a few ways to get data to inspect:
> 
> 1. Open a port-forward session to a sidecar and get a config dump
> 2. Open a port-forward session to a (new) gRPC server on the osm-controller that has a defined service for interpreting various commands.
> 3. Open a port-forward session to the sidecar-wrapper (this doesn't exist yet, but future designs are going to require a custom image that has some other processes running in the sidecar instead of vanilla envoy), that may know how to interpret some commands -- Not advocating for this yet, and we should probably hold off, or only enable with a flag being set on the mesh config.
> 4. Querying the k8s api directly and inspecting k8s objects (including status).
> 5. Creating a new Adding a new `osm-debugger` pod that can be turned up on demand that has nmap, curl, wget, nslookup etc, so users can exec into the pod, and run commands. The cli command can take multiple flags, to turn up the pod in different forms, ie: `--in-mesh --connect-to=$identity`, or `--out-of-mesh, --connect-to-all` may create the appropriate ingress backends, sidecar configs etc. It can also have a gRPC server running that can accept commands and try to detect connectivity problems.
> 
> I think it's also worth calling out exactly which scenarios we intend to provide a command to inspect/healthcheck. ie: Lack of connectivity on ingress due to misconfigured certs, misconfigred XYZ, or missing traffic policy for $service, etc

First, some background:
This troubleshooting tool is a P0 requirement for this project. We cannot afford any delays as we need to be able to troubleshoot reliably and efficiently in user environments ASAP. So we will move ahead with whatever is quick and available in terms of implementation and iterate and make improvements as necessary.

Regarding the specifics of what's an absolute must to have immediately, I have captured those scenarios [here](https://docs.google.com/document/d/1-HPGNtnch6ahYkcrjPv84UKr7AVeTO4X0Ykb1b2-zGo/edit?usp=sharing).

The tool will use k8s API, osm-controller's debug interface, and port-forwarding to the pod where necessary to retreive information to be able to verify the state of the system. At the moment we should not complicate this and use what is readily available without needing to refactor the control plane in any form.

Hope that makes sense.
