### ISSUE TITLE
[Root] Performance test & tool improvement

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#4822]
**Please describe the Improvement and/or Feature Request**

OSM load testing tool has provided scripts to do:

* Single load test job run
* Load test suite definition and execution
* Auto metrics collection

We suggest a list of further improvements to the testing tool and results analysis tasks:

### Load test tool

- [ ] [Use alternative load generation tool](https://github.com/openservicemesh/osm-perftest/issues/45), such as Fortio or Nighthawk
- [ ] [Use a single YAML file to declare the complete test suite.](https://github.com/openservicemesh/osm-perftest/issues/40) The current the test suite is defined within the full test Python script

### Result analysis automation

- [ ] [Add CI job that runs the full load test suite](https://github.com/openservicemesh/osm/issues/4872)
- [ ] [Store historical test results in persisted storage, such as Azure Storage](https://github.com/openservicemesh/osm-perftest/issues/46)
- [ ] [A tool to compare two full test results](https://github.com/openservicemesh/osm-perftest/issues/47)
- [ ] [Define alert if the difference between two runs hits a pre-defined threshold. The comparison can use the tool in from the task above.](https://github.com/openservicemesh/osm-perftest/issues/48)

### Other (optional)

- [ ] A web-based dashboard to present all historical test results 
- [ ] Compare performance with other service mesh products using the Meshery Service Mesh Performance tool
- [ ] Analyze the results from the above task

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

* Improve the automation and usability of current load test tool
* Follow up with the progress of the service mesh domain in the industry
