### ISSUE TITLE
SPIFFE support

### ISSUE THREAD

**Issue by jsturtevant** [openservicemesh/osm#5030]
Root issue for SPIFFE Support (created from research in #4750 

#### spiffe integration in OSM
> Pros and cons comparing SPIFFE to the current service identity mechanism in OSM. 

The aspects of SPIFFE that we are primarily interested in are the [x509 SVIDs](https://github.com/spiffe/spiffe/blob/main/standards/X509-SVID.md) and the [Spiffe ID](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE-ID.md).  In the future we may be interested in a few the other APIs specified but not required initially.

The SPIFFE specs doesn't specify how you use this identity just how it is encoded in the x509 certificate.  In our case we have an existing abstraction around [identity](https://github.com/openservicemesh/osm/tree/main/pkg/identity).   We don't really need to change our identity mechanism but instead make it compatible with the SPIFFE specs.  For more information on OSM identity see [identity PR](https://github.com/openservicemesh/osm/pull/5004)

Some of the benefits I see for this are: 

- By adhering to specifications it enables integrations with rest of eco system (see "Who uses SPIFFE?" at https://spiffe.io/). Once able to use the specification things like [OPA integrations](https://spiffe.io/docs/latest/microservices/envoy-opa/readme/) and [OIDC integrations](https://spiffe.io/docs/latest/keyless/oidc-federation-aws/) become options
- Opens the door for integrations with [SPIRE](https://spiffe.io/docs/latest/spire-about/). Spire has a few advantages that would likely be worth exploring further like workload attestation plugins, federation, certification rotation.  Attestation could be a big draw here.
- potential for a way to reason about using across multiple types of workload beyond kubernetes. Though the [naming schema](https://youtu.be/DXE6CDJjDV4?t=1516) is still left up to the implementors.  Our current schema might work but needs some additional thought.

> Especially explore the scenario if they are used in multi-cluster environment

At this point I believe SPIFFE isn't a requirement for multi-cluster.  It could provide a way to simplify federation and allow for [Attestation](https://spiffe.io/docs/latest/spire-about/spire-concepts/#attestation) across different platforms.    I would need to dive into the multi-cluster world more to understand what is really needed. Federation could be something really useful here.

#### tasks list
> Rough task list if we migrate from current service identity component to SPIFFE.

- [x] document current osm Identity solution #5004
- [x] Switch from `MatchSubjectAltNames` to `MatchTypedSubjectAltNames` in Envoy config #5019
- [x] #5022 
- [x] #5023 
- [x] #5024 
  - [x] #5095
- [x] #5025 
- [x] #5026 
- [x] Enable control plane certificates issue x509 SVIDS (optional)
- [ ] Implement bundle API for federation with other systems (optional)
- [ ] Integrate [envoy certificate validator](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto) (optional)
- [x] #5027 
- [ ] #5033 
- [x] #5034 
- [x] #5093

**Comment by jsturtevant** [comment]
This work is required for Spire support #5031

**Comment by jsturtevant** [comment]
A proto-type of this work can be found at https://github.com/openservicemesh/osm/compare/main...jsturtevant:osm:spiffeid?expand=1.  This could be used to do spire prototype.

**Comment by jsturtevant** [comment]
A document outlining the work required: https://docs.google.com/document/d/1WSneAPSUeZOSJLhSzGXogVLxLXCqI_NRououxdxFAl4/edit?usp=sharing

**Comment by keithmattix** [comment]
@jsturtevant It feels safe to assume that full SPIFFE support isn't part of this milestone (v1.3) correct?

**Comment by jsturtevant** [comment]
SPIFFE support could make it, depending on timeline for #5131 merging which is ready for review.  There is one more PR after that for the functionality to use the SPIFFE ID in the certs (#5025 and #5023) which I should be able to get implemented next week.   This would not include SPIRE support which requires a few refactors and Ingress work.

**Comment by jsturtevant** [comment]
spiffe certificates are now generated and used if enabled in MRC.  There are a few items in #5031 that would be needed to support SPIRE completely
