### ISSUE TITLE
Implement minimum set of Prometheus metrics for OSM Controller pod

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#902]
Metrics doc: https://docs.google.com/document/d/1wISSW9ziLy-_R6QlyTCNU2GSGwLm8EQ8VGXqi-Q0daE/edit?usp=sharing

This issue is to implement the following OSM Controller metrics and expose them via [the metrics endpoint](https://github.com/openservicemesh/osm/blob/main/pkg/httpserver/httpserver.go#L46)

- Number of Envoy proxies connected (counter could be attached [here](https://github.com/openservicemesh/osm/blob/main/pkg/envoy/ads/stream.go#L37-L40))
- Number of Envoy proxies expected to connect (certs issued; not connected yet) 
- Number of Envoy proxies disconnected (over a time window?) 
- XDS messages per second (counter could be attached [here](https://github.com/openservicemesh/osm/blob/main/pkg/envoy/ads/stream.go#L143))

---

The OSM pod has a very basic Prometheus endpoint: https://github.com/open-service-mesh/osm/blob/master/pkg/httpserver/httpserver.go#L33

We already have a [metrics store](https://github.com/openservicemesh/osm/blob/main/pkg/metricsstore/metricstore.go#L23), which is yet to be fleshed out.

**Comment by SanyaKochhar** [comment]
@snehachhabria what's the status on this?

**Comment by snehachhabria** [comment]
> @snehachhabria what's the status on this?

@SanyaKochhar we haven't yet started any work on this

**Comment by michelleN** [comment]
Next step: we need a list a metrics to return from the osm-controller

**Comment by eduser25** [comment]
Adding:
- Time bucket for envoy configuration latency times (record how much time envoy configs take)
- Number of envoy configs / s (can be calculated with the above)

**Comment by ritazh** [comment]
Adding:
Some of these can be follow up issues we add in future phases
- Number of namespaces monitored by the OSM controller
- Number and Types of SMI specs managed by the OSM controller
- Number of Ingresses observed

**Comment by michelleN** [comment]
From the estimation meeting, we'll break this up into the following tasks. Feel free to create sub issues.
- [ ] have a working prometheus endpoint
- [ ] Expose metrics related to envoy proxies
- [ ] Expose metric on latency
- [ ] Expose metrics around internal caches of resources( SMI resources, namespaces, ingresses)

**Comment by mayurigupta13** [comment]
Additional metric to collect is - How many certs are expired.

**Comment by draychev** [comment]
@mayurigupta13 this sounds interesting. How many certs have expired (and subsequently renewed) would be a function of how many side-cars we provisioned and the validity period (per cert).

A few more interesting metrics that come to mind:
 - [ ] total number of sidecars added
 - [ ] sidecars added per <time period>
 - [ ] total number of Envoy proxies connected (should match the total number of sidecars added)
 - [ ] number of Envoy proxies connecting per <time period>
 - [ ] xDS certificates issued (total and per time)
 - [ ] total service certs issued, expired, renewed
 - [ ] service certs issued, expired, renewed per <time> 
 
 
 @eduser25 from your performance work - what metrics would you recommend we add to the Prometheus endpoint of the OSM Controller?

**Comment by eduser25** [comment]
- from what mem/cpu is concerned, we are already able to capture that through k8s.
From my last post
> * Time bucket for envoy configuration latency times (record how much time envoy configs take)
> * Number of envoy configs / s (can be calculated with the above)

We probably also want:
- Number of failed XDS updates (NACKS) from envoy
- Number of XDS versioning/Nonce dropped updates
- Timebucket for webhook execution
- Number of webhooks/s (provided by the previous)
- timebucket for cert creation (track how much time does it take to create a cert)

**Comment by eduser25** [comment]
- [x] Control plane exposure (given by OSM)
  - Injector
    - [X] Injector certificate creation count and times
    - [X] Total injector webhook handling count and times
  - OSM
    - xDS path
      - [x] histogram for xDS paths, with count and success
    - Certificates
      - [ ] Service certificates creation count and times (#2606)
    - Metrics around internal caches / resources
      - [x] Namespaces on the mesh
      - [x] Services on the mesh (caveat #2604)
      - [x] Pods on the mesh (use proxy_connect_count, caveat #2604)
      - [x] other resources (Traffic splits, targets, etc. on mesh) (caveat #2604)
  
- [x] Dataplane exposure (give by envoy)
  - [X] Expose metric on latency (work complete, but requires scalability review #2498) 
  - [ ] Full context wasm stats for L7 (being worked on by @Jon #984)

- [X] document metrics with tags: https://docs.google.com/document/d/1wISSW9ziLy-_R6QlyTCNU2GSGwLm8EQ8VGXqi-Q0daE/edit#
